#Google Analytics
analytics-id: #leave blank to not use Analytics

#Subtitle
subtitle:
  active: true
  text: life and death - a journey to more consciousness

#Nav
nav:
  pages:
    active: true
  social:
    active: true

#Featured images in homepage
featured-img:
  active: true

#Show categories at the end of posts
categories:
  active: true

#Show date and read time under the post title
date-under-post:
  active: false

#Use MathJAX
mathjax:
  active: false

#Show related posts based on categories
related-posts:
  active: true
  title: "You May Also Like"

#Comments
comments: false
